services:
  app:
    build: .
    container_name: urlshortener_app
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - kafka
    environment:
      - SPRING_DATA_CASSANDRA_CONTACT_POINTS=urlshortener_cassandra
      - SPRING_DATA_CASSANDRA_PORT=9042
      - SPRING_DATA_CASSANDRA_KEYSPACE_NAME=urlshortener
      - SPRING_DATA_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_DATA_CASSANDRA_REQUEST_TIMEOUT=10s
      - SPRING_DATA_CASSANDRA_CONNECTION_CONNECT_TIMEOUT=10s
    networks:
      - urlshortener_network

  cassandra:
    image: cassandra:4.1
    container_name: urlshortener_cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=urlshortener_cluster
    volumes:
      - cassandradata:/var/lib/cassandra
      - ./init.cql:/init.cql
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    command: "bash -c 'cassandra -R -f & until cqlsh -e \"describe keyspaces\"; do echo \"Waiting for Cassandra...\"; sleep 5; done && cqlsh -f /init.cql && wait'"
    networks:
      - urlshortener_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - urlshortener_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - urlshortener_network

volumes:
  cassandradata:
networks:
  urlshortener_network:
    driver: bridge